- name: Install and set up Docker
  hosts: myhosts
  become: True
  tags: docker
  tasks:

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes
    
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present 
      
    - name: Set up stable repository for apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        # {{ ansible_distribution_release }} -> replace by host ubuntu release
        state: present
    
    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
      
    - name: Add user ubuntu to group docker
      user:
        name: ubuntu
        groups: docker
        append: yes # add user to group without removing him from other group

- name: Check docker version
  hosts: myhosts
  tags: docker_version
  tasks:
    - name: Get docker version
      shell: "docker --version"
      register: docker_version
    
    - name: Output docker version
      debug:
        var: docker_version.stdout_lines
    
    - name: Get docker compose version
      shell: "docker compose version"
      register: docker_compose_version
    
    - name: Output docker version
      debug:
        var: docker_compose_version.stdout_lines

- name: Copy docker-compose.yaml to host
  hosts: myhosts
  tags: docker_compose
  tasks:
    - name: Copy requirements folder
      copy:
        src: requirements
        dest: /home/ubuntu
        owner: ubuntu
        group: docker
      



    