- name: Install and set up Docker
  hosts: myhosts
  gather_facts: true
  become: True
  tags: set_up
  roles:
    - set_up

- name: Reset state of cloud server and reboot
  hosts: myhosts
  gather_facts: true
  become: True
  tags: reset
  roles:
    - reset
    - reboot
    
- name: Reboot cloud instance
  hosts: myhosts
  become: true
  gather_facts: false
  tags: reboot
  roles:
    - reboot
    
- name: Check docker version
  gather_facts: false
  hosts: myhosts
  tags: version
  roles:
    - version

- name: Down dockers
  gather_facts: false
  hosts: myhosts
  tags: down
  roles:
    - down

- name: Clean dockers
  gather_facts: false
  hosts: myhosts
  tags: clean
  roles:
    - clean

- name: Launch dockers
  gather_facts: false
  hosts: myhosts
  tags: up
  roles:
    - up
  