- name: My first play
  hosts: myhosts
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Print "Hello world!"
      ansible.builtin.debug:
        msg: Hello world!
    
    - name: Reboot
      ansible.builtin.reboot:
