- name: Get docker version
  shell: "docker --version"
  register: docker_version

- name: Output docker version
  debug:
    var: docker_version.stdout_lines

- name: Get docker compose version
  shell: "docker compose version"
  register: docker_compose_version

- name: Output docker version
  debug:
    var: docker_compose_version.stdout_lines
