services:

  mariadb:
    container_name: mariadb
    image: mariadb:11.4
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - cloud-1
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    image: wordpress:6.5
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - cloud-1
    healthcheck:
      test: test -f /var/www/html/wp-config.php
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}

  wordpress-cli:
    container_name: wordpress-cli
    depends_on:
      wordpress:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    build:
      context: wordpress-cli/
      dockerfile: Dockerfile
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - cloud-1
    restart: no
    user: 33:33
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    image: phpmyadmin:5.2
    networks:
      - cloud-1
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}


  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - wordpress-cli
      - phpmyadmin
    build:
      context: nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    networks:
      - cloud-1
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  mariadb_volume:
    name: mariadb_data
    driver: local

  wordpress_volume:
    name: wordpress_data
    driver: local

networks:
  cloud-1:
    name: cloud-1
    driver: bridge
