- name: Copy requirements folder
  copy:
    src: "{{ role_path }}/files/requirements"
    dest: /home/ubuntu
    owner: ubuntu
    group: docker

- name: docker compose up
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/requirements
    state: present
