services:

  mariadb:
    container_name: mariadb
    image: mariadb:11.4
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - cloud-1
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:6.5
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - cloud-1
    healthcheck:
      test: test -f /var/www/html/wp-config.php
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  wordpress-cli:
    container_name: wordpress-cli
    depends_on:
      wordpress:
        condition: service_healthy
    build:
      context: wordpress-cli/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - cloud-1
    restart: no
    user: 33:33

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - wordpress-cli
    build:
      context: nginx/
      dockerfile: Dockerfile
    networks:
      - cloud-1
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  mariadb_volume:
    name: mariadb_data
    driver: local

  wordpress_volume:
    name: wordpress_data
    driver: local

networks:
  cloud-1:
    name: cloud-1
    driver: bridge
