services:

  mariadb:
    container_name: mariaDB
    image: mariadb:11.4
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - cloud-1
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:cli
    command: ["wordpress/script/config.sh", "&&", "apache2-foreground"]
    # build:
    #   context: wordpress/
    #   dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - cloud-1
    restart: unless-stopped

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    networks:
      - cloud-1
    ports:
      - "80:80"
      # - "443:443"
    restart: unless-stopped


volumes:

  mariadb_volume:
    name: mariadb_data
    driver: local

  wordpress_volume:
    name: wordpress_data
    driver: local


networks:

  cloud-1:
    name: cloud-1
    driver: bridge
